### ISSUE TITLE
検査実施件数の日付の修正

### ISSUE THREAD

**Issue by biatunky** [covid19-aomori/website#103]
検査実施件数カードの日付が一桁の場合に0が入るのを修正する
4/01の全体累計

![image](https://user-images.githubusercontent.com/6056801/78222252-dfe48780-74ff-11ea-8032-d732856657cf.png)

**Comment by mojahige** [comment]
@biatunky
PR 作ってみました😅
お時間ある時、ご確認よろしくお願いしますー

**Comment by biatunky** [comment]
@mojahige 
ありがとうございます！
マージしました 😄
