### ISSUE TITLE
青森版相談手順の作成

### ISSUE THREAD

**Issue by biatunky** [covid19-aomori/website#11]
電話番号や相談先を確認する必要あり。
情報が不確かな場合は載せないほうが混乱を生まないかも

参考
https://stopcovid19.metro.tokyo.lg.jp/
https://ehime-covid19.com/flow

掲載していない県もあり
https://covid19-miyagi.netlify.com/
https://stopcovid19.hokkaido.dev/

**Comment by biatunky** [comment]
こちらを参考に修正をお願いします
https://aun-mypage.tools/web/visual/show/515bff897fbc6712e21ec45c5ed9001c56cf4cc3

公開前に県（？）の人にみてもらうので一旦トップページからのリンクは外してもらえると助かります〜

**Comment by biatunky** [comment]
この内容で公開OKそうです
![aa](https://user-images.githubusercontent.com/6056801/77386330-ec653380-6dcd-11ea-8702-84877ec62ebc.jpg)

**Comment by biatunky** [comment]
3/24夕方時点では一旦トップページからのリンクを外します。
ページが出来次第公開します

**Comment by biatunky** [comment]
「帰国者・接触者相談センター」の連絡先のページが独立してあるといいかなと思いました。（東京都のcontactのイメージ）

参考)東京都
https://stopcovid19.metro.tokyo.lg.jp/contacts

青森県のこのページ内の「帰国者・接触者相談センター」を参考対策サイトのフローページの下部に追加する
https://www.pref.aomori.lg.jp/welfare/health/wuhan-novel-coronavirus2020.html

**Comment by YutaSukekawa** [comment]
残タスク

* モバイル版の開発 (現在は画像ベース)
* PC 版のリファクタリング
  * 細かなレイアウトの修正 (改行ポイントなど)
  * 一部リンクが別タブで開かない (a タグに `target="_blank" rel="noopener"` を追加)
  * components/flow/FlowPc.vue 内の要素を別コンポーネントに分割する

**Comment by biatunky** [comment]
角さんより
何かのついで＆余力あったらで良いのですが、赤枠のテキストをひとまわり小さく、ウェイトノーマルにすると少しメリハリ出て読みやすくなるかと。

![0326](https://user-images.githubusercontent.com/6056801/77600269-b7322000-6f4a-11ea-8f93-91627641bf9a.png)

**Comment by biatunky** [comment]
@YutaSukekawa 
3/28 23:00の状態で本番アップしています。
もし完了ならcloseしてOKです〜

**Comment by biatunky** [comment]
問題なさそうなのでcloseします
