### ISSUE TITLE
最新のお知らせに青森県庁のコロナ関連の情報を表示

### ISSUE THREAD

**Issue by biatunky** [covid19-aomori/website#115]
コロナが含まれるRSSだけを拾ったフィード
https://siftrss.com/f/eqMXvvMA8gR

dc:subjectをtext
dc:dateをdate
rdf:aboutをurl
に入れればxmlからjsonに変換できそうなので、変換するスクリプトを作成する。

作成後にCircleCIへ組み込むことで自動で反映できるはず。

**Comment by T0date** [comment]
お知らせの表示件数ですが、最新の1件だけで良いのでしょうか。
専用の一覧ページがない以上、全件表示しておいた方が無難でしょうか？

![スクリーンショット 2020-04-14 6 21 18](https://user-images.githubusercontent.com/47016429/79162427-32834500-7e18-11ea-8249-0e5f8f55ec6a.png)

**Comment by biatunky** [comment]
表示は最新5件でいいと思います。
可能であれば、一番下に

```
青森県からの新型コロナウイルス感染症についての情報（https://www.pref.aomori.lg.jp/koho/coronavirus_index.html）
```

があると親切ですね

**Comment by biatunky** [comment]
データ更新時点で自動取得するところまでは対応できたので一旦closeします。
