### ISSUE TITLE
リンクの修正

### ISSUE THREAD

**Issue by YutaSukekawa** [covid19-aomori/website#16]
サイドナビゲーションの SNS リンクやコンテンツ内のオープンデータを入手などの各リンクの修正

**Comment by biatunky** [comment]
青森県広報統計課からの回答
```
情報発信はHPメインです。
Facebookからはコロナの情報発信することはないです。
Twitterには、県のHPが更新された時に、そのページのタイトルが自動で流れます。
```

FBとLINEは外しましょう〜

**Comment by biatunky** [comment]
2020 fukuiretu
を
2020 Aomori Hackers
に修正もお願いします

**Comment by youyo** [comment]
https://github.com/covid19-aomori/website/issues/9#issuecomment-602748477

>まだ tokyo.lg.jp , tokyo.jp がたくさん埋まってる。

探して対応する。

**Comment by biatunky** [comment]
ヘッダ周りだけになったのでこっちに引継ぎます〜

https://github.com/covid19-aomori/website/issues/19#issuecomment-603060797
