### ISSUE TITLE
OGPの修正

### ISSUE THREAD

**Issue by biatunky** [covid19-aomori/website#19]
文章
当サイトは青森県内の新型コロナウイルス感染症 (COVID-19) に関する最新情報を提供するためのサイトです。

画像
![ogp](https://user-images.githubusercontent.com/6056801/77378589-b5852280-6db9-11ea-9355-a241e2242396.png)

**Comment by fukuiretu** [comment]
こちらdevelopmentにmerge済です！

**Comment by biatunky** [comment]
すみません！
headerにtwitter:siteなど東京のものが含まれていました〜
@tokyo_bousai
https://stopcovid19.metro.tokyo.lg.jp
など

それぞれ
@AomoriPref
https://covid19-aomori.info/
に置換をお願いします！

**Comment by biatunky** [comment]
確認できたのでcloseします！
