### ISSUE TITLE
各市町村のリンク集をまとめたページを用意

### ISSUE THREAD

**Issue by fukuiretu** [covid19-aomori/website#21]
ref: https://covid19-aomori.slack.com/archives/C0109DP2T8T/p1585014418005700

**Comment by itc-okamoto** [comment]
リンク集は以下になります。
https://docs.google.com/spreadsheets/d/1RSYCfpRtNSM9MkYqurdybr5S3Ccj1R_uiWKV6n_bPRw/edit?usp=sharing

結構ボリュームあるので、ページ分けた方がいいかも。
