### ISSUE TITLE
「県内の最新感染動向」の修正

### ISSUE THREAD

**Issue by biatunky** [covid19-aomori/website#29]
##  最新のお知らせ
日付を 2020/03/24 に設定

## 注釈の修正
- オープンデータを入手 のリンクを削除
- （注）や ※1、※2 を全て削除
県のサイトに説明が出たら追加する

**Comment by biatunky** [comment]
修正に時間掛そうなので一旦1st releaseから外します

**Comment by biatunky** [comment]
フローのページへのリンク部分も一旦削除でお願いします！
https://covid19-aomori.info/flow

ページが出来次第再度リンクします〜

**Comment by YutaSukekawa** [comment]
了解です！

**Comment by youyo** [comment]
@YutaSukekawa 
#36 okです！
フローの部分も解決できたらこのissue閉じるので引き続きお願いします 🙏

**Comment by biatunky** [comment]
もう一点追加でお願いしますmm

```
２．パネルが属性と患者数だけになったので、最新のお知らせで「県から新たなデータが公表されたら随時データの追加・更新します」的なメッセージが欲しい。
```

**Comment by youyo** [comment]
#42 にて対応。

**Comment by biatunky** [comment]
確認したのcloseします
