### ISSUE TITLE
表示する情報を精査する

### ISSUE THREAD

**Issue by fukuiretu** [covid19-aomori/website#6]

**Comment by biatunky** [comment]
青森県のサイトから見つけられた情報

- 感染者情報
http://www.pref.aomori.lg.jp/soshiki/kenko/hoken/files/200323press.pdf
年代/性別/居住地/職業/経緯/現在の状況/行動歴/濃厚接触者の状況/県の対応

- 検査の実施状況
http://www.pref.aomori.lg.jp/welfare/health/wuhan-novel-coronavirus2020.html
累計件数のみ

**Comment by biatunky** [comment]
他県のサイトを参考にするとグラフ/表は以下が作れそう
- 陽性患者数
- 検査陽性者の状況
- 陽性患者の属性
- 検査実施件数

ニュースは以下から拾ってくれば良さそう
http://www.pref.aomori.lg.jp/welfare/health/

**Comment by fukuiretu** [comment]
@biatunky 調査ありがとうございます！
https://github.com/covid19-aomori/website/issues/6#issuecomment-602723632
↑ベースでちょっとグラフいじってみます！ (ぼちぼち始業なので昼休みにでも...

**Comment by fukuiretu** [comment]
@biatunky 調査ありがとうございます！
#6 (comment)
↑ベースでちょっとグラフいじってみます！ (ぼちぼち始業なので昼休みにでも...

**Comment by biatunky** [comment]
一旦OKそうなのでcloseします〜
