### ISSUE TITLE
Netlifyのビルド使いすぎ問題

### ISSUE THREAD

**Issue by youyo** [covid19-aomori/website#65]
## 課題

- Netlifyでのビルドが無料枠超えそう

![image](https://user-images.githubusercontent.com/1483901/77555323-790d1000-6efa-11ea-9739-2a8a971ee66e.png)

https://covid19-aomori.slack.com/archives/C0107RB34CB/p1585147329060500

## 解決策案

- gh-pagesを使う。東京も使いまくってた。(理由がわかった)

**Comment by biatunky** [comment]
すでにギリギリっぽいのでとりあえずbuildの追加料金払えるようにカード登録しておきました〜

**Comment by youyo** [comment]
これを参考にやってみる
https://qiita.com/nwtgck/items/e9a355c2ccb03d8e8eb0

**Comment by youyo** [comment]
circleciを使うようにして問題解決。
