### ISSUE TITLE
AomoriHackersについてaboutページへ説明を追記する

### ISSUE THREAD

**Issue by fukuiretu** [covid19-aomori/website#66]
```
ふと思ったのですが、このサイト連絡先がないので団体の実態が分かりにくいですね。
AomoriHackersのロゴとか説明文があると良さそうです。
```
ref: https://covid19-aomori.slack.com/archives/C0107RB34CB/p1585183872070900

**Comment by itc-okamoto** [comment]
私達について

私達は、青森県内のIT関係者を中心に構成されており、新型コロナウイルス感染者が青森県で確認された2020年3月23日に有志が集結し「AomoriHackers」が結成されました。
このサイトはその翌日に公開され、その後、このサイトの運営をおこなっています。

連絡先：
covid19.aomori@gmail.com

**Comment by biatunky** [comment]
ロゴも作成いただいたので、当サイトについてページに「私達について」の項目の追加をお願いします！
ロゴは、左メニューにもあるといいと思います。


https://covid19-aomori.slack.com/archives/C0107RB34CB/p1585284118119900?thread_ts=1585269237.113800&cid=C0107RB34CB
