### ISSUE TITLE
データセットの準備

### ISSUE THREAD

**Issue by fukuiretu** [covid19-aomori/website#7]
### 関連Issue
- #6 

### TODO
- どういった形で提供してもらえそうか
  - PDF?
  - EXCEL?
  - CSV?
  - API?
  - etc...
- API以外であればパーサーが必要

**Comment by fukuiretu** [comment]
memo: okamoto sanが話を持っていってくれるらしい

**Comment by youyo** [comment]
3/23の分をとりあえず手動で修正した。

**Comment by youyo** [comment]
スプレッドシートで管理する。

https://docs.google.com/spreadsheets/d/1UM8hPEsLG9zDRqvODxnldFhaUPWF1NQVvcR-6nOKlDs/edit?usp=sharing

![image](https://user-images.githubusercontent.com/1483901/77511538-9d45fe00-6eb4-11ea-9260-5623d2e820e9.png)

https://covid19-aomori.slack.com/archives/C010NRPP03Z/p1585097884000800

**Comment by youyo** [comment]
### Todo

- 松プランCの実装 https://covid19-aomori.slack.com/archives/C010RUW5QMD/p1585114808008900

>■松プランC
>- スプレッドシート更新後、GAS経由でS3にアップロード
-> S3へのアップロードをフックしてLambda経由でNetlifyのビルドを走らせる (要Build hooks

**Comment by youyo** [comment]
- @fukuiretu : GASでゴニョゴニョしてS3にアップロード
- @youyo : `s3->sns->lambda->netlify` あたりをSAMとGithubActionsでバーン

![image](https://user-images.githubusercontent.com/1483901/77515402-d46bdd80-6ebb-11ea-8e42-1ad46c8b7127.png)

https://covid19-aomori.slack.com/archives/C010RUW5QMD/p1585120714012700

**Comment by youyo** [comment]
https://github.com/covid19-aomori/gas-datasetgen
https://github.com/covid19-aomori/dataset-deployment

![image](https://user-images.githubusercontent.com/1483901/77818020-869ce280-7112-11ea-8f92-0b826d26f4b9.png)

**Comment by zenver6** [comment]
#76 
https://covid19-aomori.slack.com/archives/C0109DP2T8T/p1585436958071600

情報元のPDFにリンクを貼りたいので、data.jsonのpatientsにsourceを追加して、情報元PDFのURLを保持したい。
![スクリーンショット 2020-03-29 8 19 42](https://user-images.githubusercontent.com/10470863/77836065-2d769280-7196-11ea-9c50-2c93193e4dc8.png)

**Comment by fukuiretu** [comment]
こちら考慮済みです！
https://github.com/covid19-aomori/website/issues/7#issuecomment-605532993

**Comment by youyo** [comment]
オープンデータカタログにてデータ公開されたのでこちらを参照するように変更していく。
https://opendata.pref.aomori.lg.jp/dataset/1531.html

**Comment by youyo** [comment]
以下のように仕様変更予定
https://github.com/covid19-aomori/gas-datasetgen

### before
- GASでスプレッドシートからjson生成(手動更新)

### after
- GASでオープンデータカタログのcsvからjson生成(自動更新)

**Comment by biatunky** [comment]
構成変更完了したので閉じます
