### ISSUE TITLE
検査実施件数の日別の削除

### ISSUE THREAD

**Issue by biatunky** [covid19-aomori/website#83]
県のデータが数日まとめて更新されるため、日別のデータの表示/扱いが難しいです。
一旦、累計のみの表示に変更して、注釈に以下の文言の追加をお願いします。

```
青森県の発表日基準でのグラフとなるため土日などはまとめて週明けにカウントされます
```

![image](https://user-images.githubusercontent.com/6056801/77883785-c85a9400-729e-11ea-980c-e6980554d3c0.png)

**Comment by mojahige** [comment]
<img width="598" alt="スクリーンショット 2020-03-30 22 26 43" src="https://user-images.githubusercontent.com/13248811/77917525-a16b8480-72d5-11ea-8867-1d1033257e14.png">

はじめまして。

- 注釈追加
- 「日別」のボタンを CSS で非表示

してみました。

このような感じで大丈夫でしょうか？

**Comment by biatunky** [comment]
@mojahige 
ありがとうございます！
イメージ通りです！

PRいただければ確認しますmm

**Comment by mojahige** [comment]
@biatunky ありがとうございます〜😄
PR 作成いたしました！ (https://github.com/covid19-aomori/website/pull/88)

**Comment by biatunky** [comment]
問題なかったので本番にデプロイしました！
@mojahige ありがとうございました！

https://covid19-aomori.info/
